name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install checkinstall
        run: sudo apt install --yes --no-install-recommends checkinstall

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      - name: Package
        run: |
          echo "just an example" > description-pak
          sudo checkinstall --install=no --default -nodoc -D \
            --showinstall=no --pakdir=${{github.workspace}}/build \
            --backup=no \
            --pkgname=actions-example --pkgversion="1.0.0" \
            --pkggroup="misc" \
            --pkglicense=Unlicense --maintainer="Falk Werner" \
            -- cmake --install build
          mv {{github.workspace}}/build/*.deb {{github.workspace}}/build/actions-example.deb

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: actions-example.deb
          path: ${{github.workspace}}/build/actions-example.deb
          retention-days: 5 
          if-no-files-found: error
