name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest

    needs:
      - build
    
    steps:
      - name: Release notes
        uses: actions/download-artifact@v3
        with:
          name: actions-example.deb
    
      - name: Create Release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
          body: ${{github.ref}}
          draft: true
          prerelease: false
